name: release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Release nhctl
    runs-on: macos-latest
    steps:

      - name: Release Note
        id: release-note
        run: |
          echo "::set-output name=note::$(./release-note.sh v0.1.0 github.ref)"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          body: ${{ steps.pre-release.outputs.note }}