name: release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Release nhctl
    runs-on: macos-latest
    steps:
      - name: Get Pre Release
        id: pre-release
        run: |
          echo "::set-output name=release::$([[ github.ref =~ 'rc' ]] && echo true || echo false)"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: ${{ steps.pre-release.outputs.release }}
          body: ${{./release-note.sh}}