name: release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Release nhctl
    runs-on: macos-latest
    steps:
      - name: Build Changelog
        id: github_release
        if: "!contains(github.ref,'rc')"
        uses: mikepenz/release-changelog-builder-action@{latest-release}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          owner: "lyzhang1999"
          repo: "action"
          ignorePreReleases: "true"
          toTag: ${{ github.ref }}
          token: ${{ env.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          body: ${{steps.github_release.outputs.changelog}}